import { type NextPage } from "next";
import Head from "next/head";
// import Link from "next/link";
// import { api } from "~/utils/api";
import { SignIn } from "@clerk/nextjs";
import { SignInButton, SignOutButton } from "@clerk/nextjs";
import { useUser } from "@clerk/nextjs";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const { isSignedIn, user } = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <div>
          {!user && <SignInButton />}
          {!!user && <SignOutButton />}
          {isSignedIn && (
            <h1 className="text-4xl font-bold ">
              Hello {user.firstName}, Welcome to T3!
            </h1>
          )}
          <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
        </div>
      </main>
    </>
  );
};

export default Home;
