/* eslint-disable @next/next/no-img-element */
import { type NextPage } from "next";
import Head from "next/head";
import { SignIn } from "@clerk/nextjs";
import { SignInButton, SignOutButton } from "@clerk/nextjs";
import { useUser } from "@clerk/nextjs";
import { RouterOutputs, api } from "~/utils/api";

const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) {
    return null;
  }

  return (
    <div className="flex items-center gap-3">
      <input
        className="border-b border-black bg-transparent p-3 text-sm italic"
        placeholder="What's on your mind today?"
      />
      <img
        src={user.profileImageUrl}
        alt="profile picture"
        className="h-12 w-12 rounded-full border border-black"
      />
    </div>
  );
};

type PostWithUser = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: PostWithUser) => {
  const { title, content, author } = props;

  return (
    <div key={author?.id} className="border-b border-white p-4">
      <h2 className="text-xl font-bold">
        {title}
        <span className="text-sm italic"> by {author?.firstName}</span>
      </h2>
      <p>{content}</p>
    </div>
  );
};

const Home: NextPage = () => {
  const { data, isLoading } = api.posts.getAll.useQuery();

  const { isSignedIn, user } = useUser();

  if (isLoading) {
    return <div>Loading...</div>;
  }

  if (!data) {
    return <div>No data</div>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="mx-auto min-h-screen w-full bg-black md:max-w-2xl">
        <div className="flex w-full flex-col">
          <div className="flex w-full items-center justify-between border-b bg-white p-4 font-bold text-black ">
            {!user && <SignInButton />}
            {!!user && <SignOutButton />}
            <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
            {isSignedIn && <CreatePostWizard />}
          </div>
          <h1 className="p-4 text-center text-2xl font-bold">Posts</h1>
          <div className="flex flex-col">
            {data?.map((post) => (
              <PostView {...post} key={post.author?.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
